# Geyser_Anvil_Fix Configuration
# Created by SSQuadTeam

# Debug mode - enables verbose logging
debug: false

# Anvil settings
anvil:
  # Mode - ENABLED, DISABLED, or PERMISSION
  # ENABLED: Always enabled for Bedrock players
  # DISABLED: Disabled for all players
  # PERMISSION: Enabled only for Bedrock players with the 'geyseranvilfix.use' permission
  mode: ENABLED
  
  # Forward button - whether to show a button to switch to vanilla anvil
  forward: true