name: BedrockAnvil
version: '${version}'
main: com.ssquadteam.geyseranvilfix.GeyserAnvilFixPlugin
api-version: '1.21'
softdepend: [Geyser-Spigot, floodgate]
description: Adds a custom anvil interface for Bedrock players
author: SSQuadTeam
website: https://github.com/ssquadteam